[project]
name = "mount-squashfs-helper"
description = "Utilize squashfs filesystem archives as fuser mounts with squashfuse"
version = "1.0.0"
requires-python = ">=3.13"
dependencies = [
  "pytest>=9.0.2",
  "pytest-cov>=7.0.0",
  "pytest-mock>=3.15.1",
  "radon>=6.0.1",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
pythonpath = "src"
testpaths = ["tests"]
addopts = "--cov=src/mount_squashfs --cov-report=term-missing --cov-branch -v"
filterwarnings = "ignore::DeprecationWarning"
markers = "slow: mark tests as slow\nintegration: mark tests as integration tests\nunit: mark tests as unit tests"
